const prefix = 'VACANCIES';
export const GET_VACANCIES_REQUEST = `${prefix}/GET_VACANCIES_REQUEST`;
export const GET_VACANCIES_SUCCESS = `${prefix}/GET_VACANCIES_SUCCESS`;
export const GET_VACANCIES_FAILURE = `${prefix}/GET_VACANCIES_FAILURE`;

export const GET_VACANCY_REQUEST = `${prefix}/GET_VACANCY_REQUEST`;
export const GET_VACANCY_SUCCESS = `${prefix}/GET_VACANCY_SUCCESS`;
export const GET_VACANCY_FAILURE = `${prefix}/GET_VACANCY_FAILURE`;

export const CHANGE_FILTER_REQUEST = `${prefix}/CHANGE_FILTER_REQUEST`;
export const SET_FILTER_REQUEST = `${prefix}/SET_FILTER_REQUEST`;
export const SET_VACANCY_COUNT = `${prefix}/SET_VACANCY_COUNT`;

export const GET_VACANCIES_COUNT_REQUEST = `${prefix}/GET_VACANCIES_COUNT_REQUEST`;
export const GET_VACANCIES_COUNT_SUCCESS = `${prefix}/GET_VACANCIES_COUNT_SUCCESS`;
export const GET_VACANCIES_COUNT_FAILURE = `${prefix}/GET_VACANCIES_COUNT_FAILURE`;

export const SEND_SEND_FORM_REQUEST = `${prefix}/SEND_SEND_FORM_REQUEST`;
export const SEND_SEND_FORM_SUCCESS = `${prefix}/SEND_SEND_FORM_SUCCESS`;
export const SEND_SEND_FORM_FAILURE = `${prefix}/SEND_SEND_FORM_FAILURE`;

export const FAVORITE_TOGGLE_REQUEST = `${prefix}/FAVORITE_TOGGLE_REQUEST`;
export const FAVORITE_TOGGLE_SUCCESS = `${prefix}/FAVORITE_TOGGLE_SUCCESS`;
export const FAVORITE_TOGGLE_FAILURE = `${prefix}/FAVORITE_TOGGLE_FAILURE`;

export const COMPLAINT_REQUEST = `${prefix}/COMPLAINT_REQUEST`;
export const COMPLAINT_SUCCESS = `${prefix}/COMPLAINT_SUCCESS`;
export const COMPLAINT_FAILURE = `${prefix}/COMPLAINT_FAILURE`;
